version: "3"
services:
  database-destino:
    #build: .
    image: henrylle/babelfish
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - BABELFISH_USER=babelfish_user
      - BABELFISH_PASSWORD=babelfish
      - BABELFISH_DB=babelfish_db
      - MIGRATION_MODE=multi-db
    ports:
      - 1434:1433
      - 5433:5432
    volumes:
      - data_destino:/usr/local/pgsql/data
  database:
    #build: .
    image: henrylle/babelfish
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - BABELFISH_USER=babelfish_user
      - BABELFISH_PASSWORD=babelfish
      - BABELFISH_DB=babelfish_db
      - MIGRATION_MODE=multi-db
    ports:
      - 1433:1433
      - 5432:5432
    volumes:
      - data:/usr/local/pgsql/data
  database-sqlserver-nativo:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=@Docker!"
      - "POSTGRES_DB=bia"
    ports:
      - 1435:1433
    volumes:
      - data_sqlserver_nativo:/var/opt/mssql/data
      - bkp_sqlserver_nativo:/var/opt/mssql/bkp
volumes:
  data_destino:   
  data:
  data_sqlserver_nativo:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "D:\\sqlserver_volumes\\data_sql_server"    
  bkp_sqlserver_nativo:  
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "D:\\sqlserver_volumes\\bkp_sqlserver"
    
